name: ht_http_client
description: A Very Good Project created by Very Good CLI.
repository: https://github.com/headlines-toolkit/ht_http_client
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
